# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piaowu', '0002_auto_20180105_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yuhuataiuser',
            name='register_date',
        ),
        migrations.AddField(
            model_name='yuhuataiuser',
            name='register_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f'),
        ),
    ]
