# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piaowu', '0003_auto_20180107_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='yuhuataiuser',
            name='openid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
