# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('piaowu', '0004_yuhuataiuser_openid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=10)),
                ('card_id', models.CharField(blank=True, max_length=18)),
                ('telephone_number', models.CharField(blank=True, max_length=11)),
                ('user_uuid', models.CharField(max_length=36)),
                ('subscribe_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u9884\u7ea6\u65e5\u671f')),
                ('register_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f')),
            ],
        ),
    ]
